import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("--- Day 9: Healthcare Exploratory Data Analysis (EDA) ---\n")

# 1. Generate a Synthetic Clinical Dataset (500 Patients)
np.random.seed(42)

# Simulating realistic distributions
ages = np.random.normal(loc=55, scale=15, size=500).astype(int)
# BMI: generally normal, but we'll add some outliers
bmis = np.random.normal(loc=28, scale=6, size=500) 
# Blood Pressure naturally correlates slightly with age and heavily with BMI
blood_pressures = 80 + (ages * 0.3) + (bmis * 1.2) + np.random.normal(loc=0, scale=10, size=500)

df = pd.DataFrame({
    'Age': ages,
    'BMI': bmis,
    'Systolic_BP': blood_pressures
})

# Clean up any impossible values generated by the random distribution
df = df[(df['Age'] > 18) & (df['Age'] < 100)]

print("📊 Dataset Summary Statistics:")
print(df.describe().round(2))
print("\nGenerating Visualizations... Check your taskbar/dock for new windows!")

# 2. EDA Visualization Setup
# We will create a dashboard with 3 distinct plots
plt.figure(figsize=(15, 5))
sns.set_theme(style="whitegrid") # Makes the charts look modern

# Plot 1: Histogram (Understanding Data Distribution)
plt.subplot(1, 3, 1)
sns.histplot(df['Age'], bins=20, kde=True, color='skyblue')
plt.title('Patient Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')

# Plot 2: Scatter Plot (Finding Relationships)
# Is there a correlation between BMI and Blood Pressure?
plt.subplot(1, 3, 2)
sns.scatterplot(x='BMI', y='Systolic_BP', data=df, alpha=0.6, color='coral')
plt.title('BMI vs. Blood Pressure')
plt.xlabel('Body Mass Index (BMI)')
plt.ylabel('Systolic BP')

# Plot 3: Correlation Heatmap (Mathematical Relationships)
# 1.0 means perfect correlation, 0.0 means no relationship
plt.subplot(1, 3, 3)
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", vmin=0, vmax=1)
plt.title('Feature Correlation Heatmap')

# Automatically adjust spacing to prevent overlap
plt.tight_layout()

# 3. Display the charts!
plt.show()